version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "3000:3000"
volumes:
  db:
    driver: local
