version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - gitcollab
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./microservices/profiles/data/profiles_init.sql:/docker-entrypoint-initdb.d/profiles_init.sql
      - ./microservices/projects/data/projects_init.sql:/docker-entrypoint-initdb.d/projects_init.sql
      - ./microservices/authentication/data/auth_init.sql:/docker-entrypoint-initdb.d/auth_init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      timeout: 15s
      interval: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - gitcollab
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      timeout: 15s
      interval: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI}
      - REACT_APP_PROXY_URL=${REACT_APP_PROXY_URL}
    networks:
      - gitcollab
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    depends_on:
      backend:
        condition: service_healthy

networks:
  gitcollab:
    name: gitcollab_network

volumes:
  db:
    driver: local
