export const SIGNIN = 'auth/signin/'
export const LOGOUT = 'auth/logout/'
export const GITHUB_REDIRECT = 'auth/redirect-url/'
export const GET_PROFILE = 'profile/'
export const UPDATE_SKILLS = 'profile/skills'
export const GET_SKILLS = 'profile/get-skills'
export const UPDATE_LANGUAGES = 'profile/languages'
export const GET_LANGUAGES = 'profile/get-languages'
export const GET_USER_REPOS = 'project/github/user-repos'
export const CREATE_PROJECT = 'project/create-project'
export const SEARCH_PROJECT = 'project/search-projects'
export const USER_PROJECT = 'project/user-projects'
export const GET_PROJECT_ISSUES = 'project/github/repo-issues'
export const GET_PROJECT = "project/"
export const GET_TASKS = "/tasks/"
export const CREATE_TASK = '/tasks/new' //Needs the follow /project/${projectname}/tasks/new
